echo Building 10/Square...
../build/JackCompiler 10/Square/Main.jack 10/Square/Square.jack 10/Square/SquareGame.jack --tokenize
echo Comparing 10/Square/MainT.xml...
diff 10/Square/MainT_.xml 10/Square/MainT.xml --strip-trailing-cr
echo Comparing 10/Square/SquareT.xml...
diff 10/Square/SquareT_.xml 10/Square/SquareT.xml --strip-trailing-cr
echo Comparing 10/Square/SquareGameT.xml...
diff 10/Square/SquareGameT_.xml 10/Square/SquareGameT.xml --strip-trailing-cr

printf "\n"
echo Building 10/ExpressionLessSquare...
../build/JackCompiler 10/ExpressionLessSquare/Main.jack 10/ExpressionLessSquare/Square.jack 10/ExpressionLessSquare/SquareGame.jack --tokenize
echo Comparing 10/ExpressionLessSquare/MainT.xml...
diff 10/ExpressionLessSquare/MainT_.xml 10/ExpressionLessSquare/MainT.xml --strip-trailing-cr
echo Comparing 10/ExpressionLessSquare/SquareT.xml...
diff 10/ExpressionLessSquare/SquareT_.xml 10/ExpressionLessSquare/SquareT.xml --strip-trailing-cr
echo Comparing 10/ExpressionLessSquare/SquareGameT.xml...
diff 10/ExpressionLessSquare/SquareGameT_.xml 10/ExpressionLessSquare/SquareGameT.xml --strip-trailing-cr

printf "\n"
echo Building 10/ArrayTest...
../build/JackCompiler 10/ArrayTest/Main.jack --tokenize
echo Comparing 10/ArrayTest/MainT.xml...
diff 10/ArrayTest/MainT_.xml 10/ArrayTest/MainT.xml --strip-trailing-cr

